-- Supports a "start a book" flow that creates a books row with only what's
-- known up front (title, format_type, word_count/page_count if available),
-- leaving the rest NULL until a separate "finish" flow completes it later.
alter table books alter column author drop not null;
alter table books alter column genre drop not null;
alter table books alter column year_read drop not null;
alter table books alter column format_raw drop not null;
alter table books alter column page_count drop not null;
alter table books alter column format_type drop not null;

-- book_id was a plain integer PK with explicitly-assigned values from the
-- original import (1-224). Make it auto-generate for new rows the "start a
-- book" flow creates, without touching existing rows. GENERATED BY DEFAULT
-- (not ALWAYS) still allows an explicit id to be passed if ever needed.
alter table books alter column book_id add generated by default as identity;
select setval(pg_get_serial_sequence('books', 'book_id'), (select max(book_id) from books));
